"""Every lockfile in the repo pins the same commons, at the commit pyproject's tag resolves to.

This exists because the repo shipped a lockfile nothing watched. `requirements-dev-oidc.lock`
was not in `scripts/lock.py`'s target list and there was no `make lock` target at all, so the
only thing that ever regenerated it was somebody typing the uv command by hand. It drifted, and
kept pinning superseded builds of agent-eval-kit and hex-service-kit for as long as nobody
looked.

That is not a cosmetic drift. The commons the other lockfiles pinned is where
`EvalReport.passed` stops returning True for an EMPTY result set, and where the promotion-gate
client refuses a service response carrying no attested evidence. A CI job installing the stale
pin therefore ran against a gate client that would certify a promotion backed by nothing, with
no diff anywhere in the repo to notice, because two of the three lockfiles were correct.

So the assertions below are deliberately about the SET of lockfiles, discovered by glob rather
than listed: a new `requirements-<something>.lock` is covered the moment it is added, which is
exactly the property the hardcoded list did not have. They are cheap file reads, no network.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]

#: Every lockfile the repo ships, discovered rather than enumerated. See the module docstring.
LOCKFILES: tuple[str, ...] = tuple(sorted(p.name for p in REPO_ROOT.glob("requirements-*.lock")))

#: `<name> @ git+<url>@<ref>` as a lockfile body writes it.
_LOCK_PIN = re.compile(r"^([a-z0-9-]+) @ git\+(\S+?)@(\S+)\s*$", re.M)

#: `"<name>[extras] @ git+<url>@<tag>",` as pyproject declares it.
_DECLARED_PIN = re.compile(
    r"([a-z0-9-]+)(?:\[[^\]]*\])?\s*@\s*git\+\S+?@(v[0-9][^\s\"']*)",
)

#: The `#   <package>  v<tag> = <commit>` map the lockfile header carries.
_TAG_COMMIT_LINE = re.compile(
    r"^#\s+(?P<package>[a-z0-9-]+)\s+(?P<tag>v[0-9][^\s]*)\s*=\s*(?P<commit>[0-9a-f]{40})\s*$"
)


def locked_pins(text: str) -> dict[str, str]:
    """Package -> the git ref a lockfile BODY pins it at (comment lines cannot match)."""
    return {name: ref for name, _url, ref in _LOCK_PIN.findall(text)}


def _read(name: str) -> str:
    return (REPO_ROOT / name).read_text(encoding="utf-8")


def _declared_tags() -> dict[str, str]:
    return dict(_DECLARED_PIN.findall((REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8")))


def _tag_commit_map(text: str) -> dict[str, tuple[str, str]]:
    return {
        m["package"]: (m["tag"], m["commit"])
        for m in (_TAG_COMMIT_LINE.match(raw) for raw in text.splitlines())
        if m
    }


def test_the_repo_actually_ships_the_lockfiles_this_module_thinks_it_does() -> None:
    """A glob that matches nothing would make every test below pass by vacuum."""
    assert set(LOCKFILES) >= {
        "requirements-dev.lock",
        "requirements-gcp.lock",
        "requirements-dev-oidc.lock",
    }, f"discovered only {LOCKFILES}; the glob is not finding the lockfiles CI installs"


def test_make_lock_regenerates_every_lockfile_the_repo_ships() -> None:
    """The root cause, asserted directly: a lockfile outside `make lock` is one that drifts.

    `scripts/lock.py` is the only supported way to recompile a lockfile, because `uv pip compile`
    destroys the header. A lockfile it does not name is regenerated by hand or not at all, and
    the hand path is the one that left a superseded commons pinned in this repo.
    """
    script = (REPO_ROOT / "scripts" / "lock.py").read_text(encoding="utf-8")
    uncovered = [name for name in LOCKFILES if f'"{name}"' not in script]
    assert not uncovered, (
        f"{', '.join(uncovered)} is shipped but not a target in scripts/lock.py, so `make lock` "
        "leaves it behind and it will drift the moment a dependency is bumped"
    )
    assert re.search(r"^lock:", (REPO_ROOT / "Makefile").read_text(encoding="utf-8"), re.M), (
        "scripts/lock.py is documented as `make lock`, so the Makefile needs that target"
    )


@pytest.mark.parametrize("name", LOCKFILES)
def test_each_lockfile_pins_the_commons_by_commit_not_by_tag(name: str) -> None:
    """A tag is a movable pointer; pinning one is not a lock."""
    for package, ref in sorted(locked_pins(_read(name)).items()):
        assert re.fullmatch(r"[0-9a-f]{40}", ref), (
            f"{name} pins {package} at {ref!r}, which is not a 40-character commit sha"
        )


def test_every_lockfile_pins_each_commons_at_the_same_commit() -> None:
    """The defect this module was written for: one lockfile a release behind the others.

    Nothing else in the gate compares them, so a job installing the odd one out silently ran a
    superseded commons. Disagreement is always a bug: the lockfiles are compiled from one
    `pyproject.toml`, so the only way two can differ is that one was not recompiled.
    """
    by_file = {name: locked_pins(_read(name)) for name in LOCKFILES}
    packages = sorted({package for pins in by_file.values() for package in pins})
    assert packages, "no lockfile pins any commons; the pin regex is not matching"
    for package in packages:
        pinned = {name: pins[package] for name, pins in by_file.items() if package in pins}
        assert len(set(pinned.values())) == 1, (
            f"{package} is pinned at more than one commit across the lockfiles: "
            + ", ".join(f"{name} -> {ref}" for name, ref in sorted(pinned.items()))
        )


@pytest.mark.parametrize("name", LOCKFILES)
def test_each_locked_commit_is_recorded_against_the_tag_pyproject_names(name: str) -> None:
    """The offline proof that the pinned commit IS the tag pyproject declares.

    pyproject names a tag, because a diff of two shas tells a reviewer nothing. The lockfile
    pins the commit. The header ties the two together, and this asserts the three-way agreement
    without a network call.
    """
    text = _read(name)
    locked = locked_pins(text)
    declared = _declared_tags()
    recorded = _tag_commit_map(text)
    assert declared, "pyproject.toml declares no git-pinned commons"
    assert set(recorded) == set(locked), (
        f"{name}: the header tag map covers {sorted(recorded)} but the body pins {sorted(locked)}"
    )
    for package, (tag, commit) in sorted(recorded.items()):
        assert package in declared, f"{name} pins {package}, which pyproject.toml does not declare"
        assert commit == locked[package], (
            f"{name}: header records {package} at {commit}, the body pins {locked[package]}"
        )
        assert tag == declared[package], (
            f"{name}: header records {package} {tag}, pyproject.toml declares {declared[package]}"
        )


def test_the_comparison_can_actually_see_a_downgraded_pin() -> None:
    """Prove the parser is not the reason the checks above are green.

    A file-comparison test passes just as happily when its regex matches nothing, so this feeds
    it the exact shape of the defect (one lockfile a release behind) and asserts it is visible.
    """
    current = _read("requirements-dev.lock")
    pins = locked_pins(current)
    assert "agent-eval-kit" in pins, "the dev lock should pin agent-eval-kit"
    downgraded = current.replace(pins["agent-eval-kit"], "4" * 40)
    assert locked_pins(downgraded)["agent-eval-kit"] == "4" * 40, (
        "the parser cannot see a changed commit, so agreement between the files proves nothing"
    )
    assert locked_pins("# agent-eval-kit @ git+https://example.invalid/x@" + "5" * 40) == {}, (
        "a commented-out line is not a pin, and counting one would make the map wrong"
    )
